### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by jinglkang** [Jmendo12/evemodel#16]
Hi, i found anywhere but i did not find any example for using the evemodel (even in the R help package). Could you show me how to use it? Thanks very much!

**Comment by larsgr** [comment]
Yes, there is a need for examples. I have added an example as a vignette now.

please donwload the newwest version with
`devtools::install_github("Jmendo12/evemodel")` 

then you can open the vignette with
`vignette("EVE_example")`

**Comment by jinglkang** [comment]
Yeal, i got it. Thanks very much!
